# what is the difference between putting in `install` and `script`? the others have the install things in `script` https://github.com/openforcefield/openforcefield/blob/9949079abc64219312067ace42bcb54cef238e21/.travis.yml


language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    # - os: osx
    #   language: generic
    #   env: PYTHON_VER=3.5
    # - os: osx
    #   language: generic
    #   env: PYTHON_VER=3.6

    - os: linux
      python: 3.5
      env: PYTHON_VER=3.5
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
  - conda config --add channels conda-forge

    # Create test environment for package
  - conda create -n test python=$PYTHON_VER pip pytest pytest-cov
  - conda activate test

    # Install pip only modules
  - pip install codecov

    # Required packages
  - conda install --quiet --yes -c anaconda scipy numpy scikit-learn
  - conda install --quiet --yes -c rdkit rdkit
  - conda install --quiet --yes -c omnia mdtraj


    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --use-local cpeptools


script:
  - pytest -v --cov=cpeptools cpeptools/tests/

notifications:
    email: false

after_success:
  - codecov
