package:
  name: cpeptools
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  # host:
  #   - python
  #   - setuptools
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - rdkit
    - mdtraj

  run:
    - python
    - numpy
    - scipy
    - rdkit
    - mdtraj

test:
  requires:
    - pytest
  imports:
    - cpeptools

about:
  home: add_url_here
  license: MIT License
